name: Daemon Vault Integration Test
on: [push, pull_request]

jobs:
  daemon_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r requirements.txt fastapi uvicorn requests python-dotenv
          pip install -e .
      - name: Start mock Vault
        run: nohup python tests/vault_server.py > server.log 2>&1 &
      - name: Run daemon
        run: timeout 20s python -m genesis_cli.num_daemon || true
      - name: Check sync
        run: |
          grep -q "Vault sync received:" server.log || (echo "Sync missing" && cat server.log && exit 1)
