name: CI - Daemon Vault Integration Test

on:
  push:
    branches: [ main ]

jobs:
  daemon_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Install test dependencies
        run: |
          pip install fastapi uvicorn pytest

      - name: Start mock Vault server
        run: |
          nohup uvicorn tests.vault_server:app --port 8000 --host 0.0.0.0 &> server.log &
          sleep 2

      - name: Run daemon for a few cycles
        run: |
          timeout 20s nun --daemon --interval 5 --export tests/output.json || true

      - name: Check export file
        run: |
          if [ ! -f tests/output.json ]; then
            echo "Export file not created" && exit 1
          fi
          cat tests/output.json

      - name: Check Vault sync log
        run: |
          # Check for server receiving or client sending
          if grep -q "Vault sync received:" server.log; then
            echo "Vault sync received confirmed"
          elif grep -q "Vault sync: ✅" tests/output.json; then
            echo "Vault sync send confirmed"
          else
            echo "Vault sync did not occur" && exit 1
          fi
